#!/usr/bin/python3
import sys

def factorize(n):
    for i in range(2, n // 2 + 1):
        if n % i == 0:
            print(f"{n}={i}*{n//i}")
            return

if len(sys.argv) != 2:
    print("Usage: factors <file>")
    sys.exit(1)

try:
    with open(sys.argv[1], 'r') as file:
        for line in file:
            num = int(line.strip())
            factorize(num)
except FileNotFoundError:
    print(f"Error: {sys.argv[1]} not found")
    sys.exit(1)
